[package]
name = "helpable-derive"
version = "0.1.0"
authors = ["kunicmarko20 <kunicmarko20@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
dialoguer = "0.4.0"
github-client = "0.1.0"
syn = "1.0.5"
quote = "1.0.2"
